kind: Namespace
apiVersion: v1
metadata:
  name: meaocron
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blockaws
  namespace: meaocron
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grant-netpol-access
rules:
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "update", "create"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grant-netpol-access
subjects:
- kind: ServiceAccount
  name: blockaws
  namespace: meaocron
roleRef:
  kind: ClusterRole
  name: grant-netpol-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: blockaws-secrets
  namespace: meaocron
type: Opaque
data:
  DMS_URL: BASE_64_ENCODED_URL
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: block-aws-cron
  namespace: meaocron
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 60
      template:
        spec:
          containers:
          - name: block-aws-cron
            image: quay.io/mozmar/blockaws:7a317c6
            env:
              - name: DMS_URL
                valueFrom:
                  secretKeyRef:
                    name: blockaws-secrets
                    key: DMS_URL
          serviceAccountName: blockaws
          restartPolicy: OnFailure

